// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableWeeks() {
  return window['go']['main']['App']['GetAvailableWeeks']();
}

export function GetCurrentWeekStart() {
  return window['go']['main']['App']['GetCurrentWeekStart']();
}

export function GetHourlyTimeline() {
  return window['go']['main']['App']['GetHourlyTimeline']();
}

export function GetTodaySummary() {
  return window['go']['main']['App']['GetTodaySummary']();
}

export function GetWeeklyStats(arg1) {
  return window['go']['main']['App']['GetWeeklyStats'](arg1);
}

export function GetWeeklySummary(arg1) {
  return window['go']['main']['App']['GetWeeklySummary'](arg1);
}

export function SetBreakInterval(arg1) {
  return window['go']['main']['App']['SetBreakInterval'](arg1);
}

export function SetCategory(arg1, arg2) {
  return window['go']['main']['App']['SetCategory'](arg1, arg2);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
