// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function GetAvailableWeeks():Promise<Array<string>>;

export function GetCurrentWeekStart():Promise<string>;

export function GetHourlyTimeline():Promise<Array<db.HourlySlot>>;

export function GetTodaySummary():Promise<Array<db.DailySummary>>;

export function GetWeeklyStats(arg1:string):Promise<db.WeeklyStats>;

export function GetWeeklySummary(arg1:string):Promise<Array<db.DailySummary>>;

export function SetBreakInterval(arg1:number):Promise<void>;

export function SetCategory(arg1:string,arg2:string):Promise<void>;

export function TogglePause():Promise<boolean>;
